sudo: required
services:
  - docker

before_install:
  - docker build -t drjucker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run drjucker/react-test npm run test -- --coverage

after_success:
  - docker build -t drjucker/multi-client ./client
  - docker build -t drjucker/multi-nginx ./nginx
  - docker build -t drjucker/multi-server ./server
  - docker build -t drjucker/multi-worker ./worker
  # Log in to Docker cli
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  # Take those images and push them to DockerHub
  - docker push drjucker/multi-client
  - docker push drjucker/multi-nginx
  - docker push drjucker/multi-server
  - docker push drjucker/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker-playground
  env: MultiDockerPlayground-env
  bucket_name: elasticbeanstalk-us-east-2-475020169766
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY